config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'

  get 'profiles/:id' => 'profiles#show', as: :profile

  get 'profiles' => 'profiles#index'

  root 'tweets#index'

  resources :tweets do
    resource :likes
  end

  resources :relationships

  devise_for :users

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user # The user that initiates the follow (stalker)
  belongs_to :friend, class_name: "User" # This is the user being followed
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :likes

  validates :message,
              presence: true,
              length: {
                maximum: 140,
                too_long: 'A tweet is only 140 characters max.'
              }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships

  has_many :inverse_relationships,
              class_name: "Relationship",
              foreign_key: :friend_id
  has_many :inverse_friends,
              through: :relationships,
              source: :user
  has_many :likes

  validates :username,
              presence: true,
              uniqueness: true


  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(
          { roles: [] },
          :email,
          :password,
          :password_confirmation,
          :name,
          :username,
          :bio,
          :location ) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(
          :email,
          :password,
          :password_confirmation,
          :current_password,
          :name,
          :username,
          :bio,
          :location ) }

  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet

  def create
    @tweet.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @relationship = current_user.relationships.build(friend_id: params[:friend_id])

    if @relationship.save
      flash[:notice] = "Followed successfully."
      redirect_to profile_path(current_user.id)
    else
      flash[:notice] = "Unable to follow."
      redirect_to root_path
    end
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.destroy
    flash[:notice] = "Your relationship has been COMPLETELY destroyed"
    redirect_to profile_path(current_user.id)
  end

  private

  def relationship_params
    params.require(:relationship).permit(:user_id, :friend_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.all
  end

  def show
    #  before_action @tweet = Tweet.find(params[:id])
  end

  def edit
    # before_action @tweet = Tweet.find(params[:id])
  end

  def update
    # before_action @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet updated' }
      else
        format.html { render :edit }
      end
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet saved' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    # before_action @tweet = Tweet.find(params[:id])

    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Destruction complete!' }
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Not Really Twitter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <!-- *************** -->
      <!-- * Left Navbar * -->
      <!-- *************** -->
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(tweets_path) %>"><%= link_to 'Tweets', tweets_path %></li>
        <li class="<%= 'active' if current_page?(profiles_path) %>"><%= link_to 'Profiles', profiles_path %></li>
      </ul>
      <!-- **************** -->
      <!-- * Right Navbar * -->
      <!-- **************** -->

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
          <%= link_to 'Sign Out',
                          destroy_user_session_path,
                          method: :delete %>
          </li>
        <% else %>
          <li>
          <%= link_to 'Sign In',
                        new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThisIsDefinitelyNotTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <p id="notice"><%= notice %></p>

  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/profiles/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %><br>
<% end %>

app/views/profiles/show.html.erb
<div class="row">
  <div class="col-xs-4">
    <h3><%= @user.name %></h3>
    <h5><%= @user.username %></h5>
    <h5><p><%= @user.bio %></p></h5>
    <h5><%= @user.location %></h5>
    <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

    <%= @user.relationships.count %> Following
    <br>
    <% @user.relationships.each do |relationship| %>
      <%= link_to relationship.friend.name, profile_path(relationship.friend) %><br>
    <% end %>
    <br>
    <br>
    <%= pluralize(@user.inverse_relationships.count, "Follower") %>
    <br>
    <% @user.inverse_friends.each do |friend| %>
      <%= link_to friend.name, profile_path(friend) %><br>
    <% end %>
  </div>

  <div class="col-xs-7">
    <div class="panel panel-default">
      <% @user.tweets.each do |tweet| %>
        <div class="panel-body">
          <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
          <br>
          <br>
          <%= tweet.message %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to "Unfollow",
        relationship_path(current_user.relationships.find_by_friend_id(@user)),
        method: :delete %>
  <% else %>
    <%= link_to "Follow",
                  relationships_path(friend_id: @user),
                  method: :post %>
  <% end %>
<% end %>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
  <%= link_to "Unlike", tweet_likes_path(@tweet), method: :delete %>
<% else %>
  <%= link_to "Like", tweet_likes_path(@tweet), method: :post %>
<% end %>

<%= @tweet.likes.count %>

Liked by:
<% @tweet.likes.each do |like| %>
  <br>
  <%= like.user.username %>
  <br>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <!-- Check for Errors and Show Us -->
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:
      </h2>

      <!-- This loops through the errors and lists them for us -->
      <ul>
        <% @tweet.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- ********************** -->
  <!-- * The Actual Form... * -->
  <!-- ********************** -->
  <div class="field form-group">
    <%= f.label :message %><br>
    <%= f.text_field :message, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="action form-group">
    <%= f.submit class: "btn btn-sm btn-success" %>
  </div>

<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show This Tweet',
            @tweet,
            class: 'btn btn-sm btn-default' %>

<%= link_to 'See All The Tweets',
            tweets_path,
            class: 'btn btn-sm btn-default' %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All The Tweets In The Universe!</h1>

<%= link_to 'New Tweet', new_tweet_path, class: "btn btn-success btn-md" %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user.username %></td>
        <td><%= link_to 'Show',
                        tweet,
                        class: "btn btn-xs btn-default" %></td>
        <td><%= link_to 'Edit',
                        edit_tweet_path(tweet),
                        class: "btn btn-xs btn-default"  %></td>
        <td><%= link_to 'Destroy',
                        tweet,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'See All The Tweets',
            tweets_path,
            class: "btn btn-default btn-sm" %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message: </strong><%= @tweet.message %>
</p>

<p>
  <strong>User: </strong><%= @tweet.user.username %>
</p>

<%= render 'shared/likes' %>
<br>
<%= link_to 'Edit This Tweet',
            edit_tweet_path(@tweet),
            class: "btn btn-sm btn-default" %>
<%= link_to 'See All The Tweets',
            tweets_path,
            class: "btn btn-sm btn-default" %>